baseurl: "" # the subpath of your site, e.g. /blog
url: "https://guidepost.design" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

sass:
  sass_dir: assets/css

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "base"
      hiddable_header: "false"
      guidepost_location: "Koh Tao, TH"
      guidepost_timezone: "Asia/Bangkok"
      guidepost_lat: "10.081729"
      guidepost_lng: "99.824654"

collections:
  journal:
    output: true
    permalink: /journal/:path
  portfolio:
    output: true
    permalink: /portfolio/:path

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
