baseurl: "" # the subpath of your site, e.g. /blog
url: "https://guidepost.design" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

sass:
  sass_dir: assets/css

# Clock configuration
guidepost_location: "Istanbul, Turkey"
guidepost_timezone: "Asia/Istanbul"
guidepost_lat: "41.028216"
guidepost_lng: "28.972579"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "base"
      hiddable_header: "false"

collections:
  journal:
    output: true
    permalink: /journal/:path

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.txt
  - README.md
