baseurl: "" # the subpath of your site, e.g. /blog
url: "https://guidepost.design" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

sass:
  sass_dir: assets/css

collections:
  log:
    output: true
    permalink: /log/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
